adminUser:
  password: vault:riderforest/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: muirp-owner@bleepbleep.org.uk
  token: vault:riderforest/pipelineUser:token
  username: muirp-owner
prow:
  hmacToken: vault:riderforest/prow:hmacToken
