adminUser:
  password: local:riderforest/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: muirp-owner@bleepbleep.org.uk
  token: local:riderforest/pipelineUser:token
  username: muirp-owner
prow:
  hmacToken: local:riderforest/prow:hmacToken
